### ISSUE TITLE
Can't add it to netbeans

### ISSUE THREAD

**Issue by drashti4** [sagiegurari/fax4j#1]
I have added this zip file in library in my netbeans project but it shows error on FaxClient,FaxJob,FaxJobPriority.I'm using maven so i have add dependency according to your notes but still not work

**Comment by sagiegurari** [comment]
if you are using maven, you only need to add the dependency to your pom.xml and no need to download any zip.
I'm not working with netbeans, but with past experience of eclipse that had many issues (the maven plugin in eclipse), i had to manually run "maven install" to make maven download the dependencies since eclipse maven plugin didn't do it (don't know why).

so I suggest you go to the root of your project where you have a pom.xml and you added the dependency and than write maven install.

by the way if the maven install works for you than your code also compiles fine with fax4j.
